name: Lint

on: 
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install ClangFormat
        run: sudo apt-get install -y clang-format-13

      - name: Run linters
        uses: wearerequired/lint-action@v2
        checks: write
        with:
          clang_format: true 