name: Unit Tests

on: 
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  ci:
    name: Run Unit Tests
    runs-on: ubuntu-20.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Godot
        uses: lihop/setup-godot@v2
        with:
          version: 4.2.1-stable

      - name: Set up Python (for SCons)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install scons
        run: |
          python -m pip install scons

      - name: Build module
        run: |
          cd godot-cpp
          scons platform=linux target=template_debug
          cd ..
          scons platform=linux target=template_debug disable_exceptions=no build_library=no tests=1

      - name: Run tests
        run: |
          set -e
          godot --no-window -T